apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: spillerom-demo
  namespace: speilvendt
  annotations:
    snorlax.nais.io/enabled: 'false'
  labels:
    team: speilvendt
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - https://spillerom.ekstern.dev.nav.no
  replicas:
    min: 1
    max: 1
    scalingStrategy:
      cpu:
        thresholdPercentage: 90
  preStopHook:
    http:
      path: /api/internal/preStop
      port: 3000
  accessPolicy:
    outbound:
      rules:
        - application: bakrommet
      external:
        - host: sp-kodeverk.ekstern.dev.nav.no
  resources:
    limits:
      memory: 350Mi
    requests:
      cpu: 50m
      memory: 256Mi
  liveness:
    path: /api/internal/isAlive
  readiness:
    path: /api/internal/isAlive
  startup:
    path: /api/internal/isAlive
    initialDelay: 10
