apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: spillerom
  namespace: speilvendt
  annotations:
    snorlax.nais.io/enabled: 'false'
  labels:
    team: speilvendt
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - https://spillerom.ansatt.dev.nav.no
  replicas:
    min: 1
    max: 1
    scalingStrategy:
      cpu:
        thresholdPercentage: 90
  preStopHook:
    http:
      path: /api/internal/preStop
      port: 3000
  azure:
    application:
      tenant: trygdeetaten.no
      enabled: true
      allowAllUsers: true # TODO sett opp brukergrupper
    sidecar:
      enabled: true
      autoLogin: true # TODO heller redirecte selv fra next koden?
  resources:
    limits:
      memory: 350Mi
    requests:
      cpu: 50m
      memory: 256Mi
  liveness:
    path: /api/internal/isAlive
  readiness:
    path: /api/internal/isAlive
  startup:
    path: /api/internal/isAlive
    initialDelay: 10
