apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: spillerom
  namespace: speilvendt
  annotations:
    snorlax.nais.io/enabled: 'false'
  labels:
    team: speilvendt
spec:
  image: {{image}}
  port: 3000
  ingresses:
    - https://spillerom.ansatt.dev.nav.no
    - https://spillerom.intern.dev.nav.no
  replicas:
    min: 2
    max: 3
    scalingStrategy:
      cpu:
        thresholdPercentage: 90
  preStopHook:
    http:
      path: /api/internal/preStop
      port: 3000
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      allowAllUsers: false
      claims:
        extra:
          - 'NAVident'
        groups:
          - id: '4373da97-ad06-40c0-893e-98ba4d0aeecb' # helse-spillerom-saksbehandler
          - id: '50522674-8a68-467d-8689-c71074a84dcc' # helse-spillerom-beslutter
          - id: '101064bf-99ea-40a2-9285-e38cfbb74f10' # helse-spillerom-lesemodus
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /_next/*
        - /public/*
  resources:
    limits:
      memory: 350Mi
    requests:
      cpu: 50m
      memory: 256Mi
  liveness:
    path: /api/internal/isAlive
  readiness:
    path: /api/internal/isAlive
  startup:
    path: /api/internal/isAlive
    initialDelay: 10
  accessPolicy:
    outbound:
      rules:
        - application: bakrommet
      external:
        - host: sp-kodeverk.ekstern.dev.nav.no
  env:
    - name: BAKROMMET_SCOPE
      value: api://dev-gcp.speilvendt.bakrommet/.default
    - name: BAKROMMET_HOST
      value: bakrommet
    - name: MODIA_BASE_URL
      value: http://modiacontextholder.personoversikt
    - name: MODIA_SCOPE
      value: api://dev-gcp.personoversikt.modiacontextholder/.default
