name: "Installs node, installs pnpm dependencies with cache"
description: "Requires NPM_AUTH_TOKEN - Sets up Node.js 24 and installs dependencies"

inputs:
  NPM_AUTH_TOKEN:
    required: true
    description: "NPM authentication token"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v5
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: pnpm
    - shell: bash
      env:
        NPM_AUTH_TOKEN: ${{ inputs.NPM_AUTH_TOKEN }}
      run: pnpm install --frozen-lockfile
