name: "Installs node, installs pnpm dependencies with cache"
description: "Builds a Next.JS App, creates a docker image and uploads it to GAR"

inputs:
  NPM_AUTH_TOKEN:
    required: true
    description: "NPM authentication token"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - id: corepack
      shell: bash
      run: corepack enable
    - uses: actions/setup-node@v4
      id: setup-node
      with:
        node-version: 24
        cache: pnpm
    - id: set-env
      shell: bash
      run: echo "NPM_AUTH_TOKEN=${{ inputs.NPM_AUTH_TOKEN }}" >> $GITHUB_ENV
    - id: pnpm-install
      shell: bash
      run: pnpm install --frozen-lockfile

