import { Ainntekt } from '@/schemas/ainntekt'

export const ainntektData: Ainntekt = {
    data: [
        {
            maaned: '2024-09',
            opplysningspliktig: '963743254',
            underenhet: '896929119',
            norskident: '11847996775',
            oppsummeringstidspunkt: '2025-10-23T13:03:42.578Z',
            inntektListe: [
                {
                    type: 'Loennsinntekt',
                    beloep: 40000,
                    fordel: 'kontantytelse',
                    beskrivelse: 'fastloenn',
                    inngaarIGrunnlagForTrekk: true,
                    utloeserArbeidsgiveravgift: true,
                },
            ],
            forskuddstrekkListe: [],
            avvikListe: [],
        },
        {
            maaned: '2024-10',
            opplysningspliktig: '963743254',
            underenhet: '896929119',
            norskident: '11847996775',
            oppsummeringstidspunkt: '2025-10-23T13:03:42.578Z',
            inntektListe: [
                {
                    type: 'Loennsinntekt',
                    beloep: 40000,
                    fordel: 'kontantytelse',
                    beskrivelse: 'fastloenn',
                    inngaarIGrunnlagForTrekk: true,
                    utloeserArbeidsgiveravgift: true,
                },
            ],
            forskuddstrekkListe: [],
            avvikListe: [],
        },
        {
            maaned: '2024-11',
            opplysningspliktig: '963743254',
            underenhet: '896929119',
            norskident: '11847996775',
            oppsummeringstidspunkt: '2025-10-23T13:03:42.578Z',
            inntektListe: [
                {
                    type: 'Loennsinntekt',
                    beloep: 40000,
                    fordel: 'kontantytelse',
                    beskrivelse: 'fastloenn',
                    inngaarIGrunnlagForTrekk: true,
                    utloeserArbeidsgiveravgift: true,
                },
            ],
            forskuddstrekkListe: [],
            avvikListe: [],
        },
        {
            maaned: '2024-12',
            opplysningspliktig: '963743254',
            underenhet: '896929119',
            norskident: '11847996775',
            oppsummeringstidspunkt: '2025-10-23T13:03:42.578Z',
            inntektListe: [
                {
                    type: 'Loennsinntekt',
                    beloep: 40000,
                    fordel: 'kontantytelse',
                    beskrivelse: 'fastloenn',
                    inngaarIGrunnlagForTrekk: true,
                    utloeserArbeidsgiveravgift: true,
                },
            ],
            forskuddstrekkListe: [],
            avvikListe: [],
        },
        {
            maaned: '2025-01',
            opplysningspliktig: '963743254',
            underenhet: '896929119',
            norskident: '11847996775',
            oppsummeringstidspunkt: '2025-10-23T13:03:42.578Z',
            inntektListe: [
                {
                    type: 'Loennsinntekt',
                    beloep: 40000,
                    fordel: 'kontantytelse',
                    beskrivelse: 'fastloenn',
                    inngaarIGrunnlagForTrekk: true,
                    utloeserArbeidsgiveravgift: true,
                },
            ],
            forskuddstrekkListe: [],
            avvikListe: [],
        },
        {
            maaned: '2025-02',
            opplysningspliktig: '963743254',
            underenhet: '896929119',
            norskident: '11847996775',
            oppsummeringstidspunkt: '2025-10-23T13:03:42.578Z',
            inntektListe: [
                {
                    type: 'Loennsinntekt',
                    beloep: 40000,
                    fordel: 'kontantytelse',
                    beskrivelse: 'fastloenn',
                    inngaarIGrunnlagForTrekk: true,
                    utloeserArbeidsgiveravgift: true,
                },
            ],
            forskuddstrekkListe: [],
            avvikListe: [],
        },
        {
            maaned: '2025-03',
            opplysningspliktig: '963743254',
            underenhet: '896929119',
            norskident: '11847996775',
            oppsummeringstidspunkt: '2025-10-23T13:03:42.578Z',
            inntektListe: [
                {
                    type: 'Loennsinntekt',
                    beloep: 40000,
                    fordel: 'kontantytelse',
                    beskrivelse: 'fastloenn',
                    inngaarIGrunnlagForTrekk: true,
                    utloeserArbeidsgiveravgift: true,
                },
            ],
            forskuddstrekkListe: [],
            avvikListe: [],
        },
        {
            maaned: '2025-04',
            opplysningspliktig: '963743254',
            underenhet: '896929119',
            norskident: '11847996775',
            oppsummeringstidspunkt: '2025-10-23T13:03:42.578Z',
            inntektListe: [
                {
                    type: 'Loennsinntekt',
                    beloep: 40000,
                    fordel: 'kontantytelse',
                    beskrivelse: 'fastloenn',
                    inngaarIGrunnlagForTrekk: true,
                    utloeserArbeidsgiveravgift: true,
                },
            ],
            forskuddstrekkListe: [],
            avvikListe: [],
        },
        {
            maaned: '2025-05',
            opplysningspliktig: '963743254',
            underenhet: '896929119',
            norskident: '11847996775',
            oppsummeringstidspunkt: '2025-10-23T13:03:42.578Z',
            inntektListe: [
                {
                    type: 'Loennsinntekt',
                    beloep: 40000,
                    fordel: 'kontantytelse',
                    beskrivelse: 'fastloenn',
                    inngaarIGrunnlagForTrekk: true,
                    utloeserArbeidsgiveravgift: true,
                },
            ],
            forskuddstrekkListe: [],
            avvikListe: [],
        },
        {
            maaned: '2025-06',
            opplysningspliktig: '963743254',
            underenhet: '896929119',
            norskident: '11847996775',
            oppsummeringstidspunkt: '2025-10-23T13:03:42.578Z',
            inntektListe: [
                {
                    type: 'Loennsinntekt',
                    beloep: 40000,
                    fordel: 'kontantytelse',
                    beskrivelse: 'fastloenn',
                    inngaarIGrunnlagForTrekk: true,
                    utloeserArbeidsgiveravgift: true,
                },
            ],
            forskuddstrekkListe: [],
            avvikListe: [],
        },
        {
            maaned: '2025-07',
            opplysningspliktig: '963743254',
            underenhet: '896929119',
            norskident: '11847996775',
            oppsummeringstidspunkt: '2025-10-23T13:03:42.578Z',
            inntektListe: [
                {
                    type: 'Loennsinntekt',
                    beloep: 40000,
                    fordel: 'kontantytelse',
                    beskrivelse: 'fastloenn',
                    inngaarIGrunnlagForTrekk: true,
                    utloeserArbeidsgiveravgift: true,
                },
            ],
            forskuddstrekkListe: [],
            avvikListe: [],
        },
        {
            maaned: '2025-08',
            opplysningspliktig: '963743254',
            underenhet: '896929119',
            norskident: '11847996775',
            oppsummeringstidspunkt: '2025-10-23T13:03:42.578Z',
            inntektListe: [
                {
                    type: 'Loennsinntekt',
                    beloep: 40000,
                    fordel: 'kontantytelse',
                    beskrivelse: 'fastloenn',
                    inngaarIGrunnlagForTrekk: true,
                    utloeserArbeidsgiveravgift: true,
                },
            ],
            forskuddstrekkListe: [],
            avvikListe: [],
        },
        {
            maaned: '2025-09',
            opplysningspliktig: '963743254',
            underenhet: '896929119',
            norskident: '11847996775',
            oppsummeringstidspunkt: '2025-10-23T13:03:42.578Z',
            inntektListe: [
                {
                    type: 'Loennsinntekt',
                    beloep: 40000,
                    fordel: 'kontantytelse',
                    beskrivelse: 'fastloenn',
                    inngaarIGrunnlagForTrekk: true,
                    utloeserArbeidsgiveravgift: true,
                },
            ],
            forskuddstrekkListe: [],
            avvikListe: [],
        },
    ],
}
