import { BeregningsreglerArray } from '@schemas/beregningsregler'

export const beregningsregler: BeregningsreglerArray = [
    {
        kode: 'ARBEIDSTAKER_100',
        beskrivelse: '(temp)Til arbeidstakere ytes det sykepenger med 100 prosent av sykepengegrunnlaget',
        vilkårshjemmel: {
            lovverk: 'Folketrygdloven',
            lovverksversjon: '1997-05-01',
            kapittel: '8',
            paragraf: '16',
            ledd: '1',
            setning: null,
            bokstav: null,
        },
        sistEndretAv: 'Redacted Redactesen',
        sistEndretDato: '2025-10-22T10:18:14.357Z',
    },
    {
        kode: 'ARB_SPG_HOVEDREGEL',
        beskrivelse:
            'Når trygden yter sykepenger, fastsettes sykepengegrunnlaget ut fra den aktuelle månedsinntekten (§§ 8-28 og 8-29), som omregnes til årsinntekt',
        vilkårshjemmel: {
            lovverk: 'Folketrygdloven',
            lovverksversjon: '2019-01-01',
            kapittel: '8',
            paragraf: '30',
            ledd: '1',
            setning: null,
            bokstav: null,
        },
        sistEndretAv: 'Redacted Redactesen',
        sistEndretDato: '2025-10-20T11:46:39.748Z',
    },
    {
        kode: 'ARB_SPG_SKJOENN_AVVIK',
        beskrivelse: 'Skjønnsfastsatt sykepengegrunnlag for arbeidstakere,  grunnet 25 prosent avvik',
        vilkårshjemmel: {
            lovverk: 'Folkretrygdloven',
            lovverksversjon: '2019-01-01',
            kapittel: '8',
            paragraf: '30',
            ledd: '2',
            setning: null,
            bokstav: null,
        },
        sistEndretAv: 'Redacted Redactesen',
        sistEndretDato: '2025-10-22T11:15:20.861Z',
    },
    {
        kode: 'ARB_SPG_SKJOENN_URIKTIG',
        beskrivelse:
            'Skjønnsfastsatt sykepengegrunnlag for arbeidstakere, grunnet mangelfull eller uriktig rapportering til a-ordningen',
        vilkårshjemmel: {
            lovverk: 'Folketrygdloven',
            lovverksversjon: '2019-01-01',
            kapittel: '8',
            paragraf: '30',
            ledd: '3',
            setning: null,
            bokstav: null,
        },
        sistEndretAv: 'Redacted Redactesen',
        sistEndretDato: '2025-10-22T11:16:11.633Z',
    },
    {
        kode: 'ARB_SPG_TIDSBEGRENSET_FOER_SLUTTDATO',
        beskrivelse:
            'Sykepengegrunnlag for det tidsrommet arbeidsforholdet skulle ha vært, arbeidstaker i et tidsbegrenset arbeidsforhold på under seks måneder',
        vilkårshjemmel: {
            lovverk: 'Folketrygdloven',
            lovverksversjon: '2019-01-01',
            kapittel: '8',
            paragraf: '30',
            ledd: '4',
            setning: '1 og 2',
            bokstav: null,
        },
        sistEndretAv: 'Redacted Redactesen',
        sistEndretDato: '2025-10-22T11:20:08.930Z',
    },
    {
        kode: 'ARB_SPG_TIDSBEGRENSET_ETTER_SLUTTDATO',
        beskrivelse:
            'Skjønnsfastsatt sykepengegrunnlag utenfor tidsrom arbeidsforholdet skulle ha vært, arbeidstaker i et tidsbegrenset forhold på under seks måneder',
        vilkårshjemmel: {
            lovverk: 'Folketrygdloven',
            lovverksversjon: '2019-01-01',
            kapittel: '8',
            paragraf: '30',
            ledd: '4',
            setning: '3',
            bokstav: null,
        },
        sistEndretAv: 'Redacted Redactesen',
        sistEndretDato: '2025-10-22T11:22:11.958Z',
    },
    {
        kode: 'SN_SPG_HOVEDREGEL',
        beskrivelse:
            'Sykepengegrunnlaget skal svare til den pensjonsgivende årsinntekten som beregnes på grunnlag av gjennomsnittet av den pensjonsgivende årsinntekten som er fastsatt for de tre siste årene',
        vilkårshjemmel: {
            lovverk: 'Folketrygdloven',
            lovverksversjon: '1997-05-01',
            kapittel: '8',
            paragraf: '35',
            ledd: '2',
            setning: '',
            bokstav: null,
        },
        sistEndretAv: 'Redacted Redactesen',
        sistEndretDato: '2025-10-23T05:14:47.844Z',
    },
    {
        kode: 'SN_SPG_SKJOENN_VARIG_ENDRING',
        beskrivelse: 'Skjønnsfastsatt sykepengegrunnlag for SN, grunnet 25 prosent avvik',
        vilkårshjemmel: {
            lovverk: 'Folketrygdloven',
            lovverksversjon: '2019-01-01',
            kapittel: '8',
            paragraf: '35',
            ledd: '3',
            setning: null,
            bokstav: null,
        },
        sistEndretAv: 'Redacted Redactesen',
        sistEndretDato: '2025-10-22T10:38:05.471Z',
    },
    {
        kode: 'SN_SPG_SKJOENN_NYIARB',
        beskrivelse: 'Skjønnsfastsatt sykepengegrunnlag for SN, grunnet ny i arbeidslivet',
        vilkårshjemmel: {
            lovverk: 'Folketrygdloven',
            lovverksversjon: '2019-01-01',
            kapittel: '8',
            paragraf: '35',
            ledd: '3',
            setning: '2',
            bokstav: null,
        },
        sistEndretAv: 'Redacted Redactesen',
        sistEndretDato: '2025-10-22T11:03:51.969Z',
    },
    {
        kode: 'ORDINAER_SELVSTENDIG_NAVFORSIKRING_100',
        beskrivelse:
            '(Temp)En selvstendig næringsdrivende kan mot særskilt premie tegne forsikring som kan omfatte sykepenger med 100 prosent av sykepengegrunnlaget fra 17. sykedag eller sykepenger med 100 prosent av sykepengegrunnlaget fra første sykedag',
        vilkårshjemmel: {
            lovverk: 'Folketrygdloven',
            lovverksversjon: '1999-10-01',
            kapittel: '8',
            paragraf: '36',
            ledd: '1',
            setning: null,
            bokstav: 'b-c',
        },
        sistEndretAv: 'Redacted Redactesen',
        sistEndretDato: '2025-10-22T11:03:51.969Z',
    },
    {
        kode: 'SELVSTENDIG_KOLLEKTIVFORSIKRING_100',
        beskrivelse:
            '(temp) Spesielle yrkesgrupper kan tegne kollektiv forsikring (jordbruker, reindriftsutøver og fisker)',
        vilkårshjemmel: {
            lovverk: 'Folketrygdloven',
            lovverksversjon: '1999-10-01',
            kapittel: '8',
            paragraf: '36',
            ledd: '4',
            setning: null,
            bokstav: null,
        },
        sistEndretAv: 'Redacted Redactesen',
        sistEndretDato: '2025-10-22T11:03:51.969Z',
    },
    {
        kode: 'FRILANSER_100',
        beskrivelse: '(temp)Til en frilanser ytes det sykepenger med 100 prosent av sykepengegrunnlaget',
        vilkårshjemmel: {
            lovverk: 'Folketrygdloven',
            lovverksversjon: '1997-05-01',
            kapittel: '8',
            paragraf: '38',
            ledd: '1',
            setning: '1',
            bokstav: null,
        },
        sistEndretAv: 'Redacted Redactesen',
        sistEndretDato: '2025-10-22T11:03:51.969Z',
    },
    {
        kode: 'KOMBI_A_SN_SPG',
        beskrivelse: 'Sykepengegrunnlag kombinerte inntekter som arbeidstaker og selvstendig næringsgivende',
        vilkårshjemmel: {
            lovverk: 'Folketrygdloven ',
            lovverksversjon: '2023-01-01',
            kapittel: '8',
            paragraf: '41',
            ledd: '3',
            setning: null,
            bokstav: null,
        },
        sistEndretAv: 'Redacted Redactesen',
        sistEndretDato: '2025-10-22T11:14:20.391Z',
    },
    {
        kode: 'INAKTIV_65',
        beskrivelse:
            'For yrkesaktive medlemmer som midlertidig har vært ute av inntektsgivende arbeid og som fremdeles e(Temp) ute av inntektsgivende arbeid utgjør sykepengene 65 prosent av sykepengegrunnlaget',
        vilkårshjemmel: {
            lovverk: 'Folketrygdloven',
            lovverksversjon: '2020-01-01',
            kapittel: '8',
            paragraf: '47',
            ledd: '6',
            setning: '2',
            bokstav: null,
        },
        sistEndretAv: 'Redacted Redactesen',
        sistEndretDato: '2025-10-22T11:14:20.391Z',
    },
    {
        kode: 'INAKTIV_100',
        beskrivelse:
            '(temp)For yrkesaktive medlemmer som midlertidig har vært ute av inntektsgivende arbeid og som er i arbeid uten å fylle vilkåret i § 8-2 om fire ukers opptjeningstid utgjør sykepengene 100 prosent av sykepengegrunnlaget',
        vilkårshjemmel: {
            lovverk: 'Folketrygdloven',
            lovverksversjon: '2020-01-01',
            kapittel: '8',
            paragraf: '47',
            ledd: '6',
            setning: '3',
            bokstav: null,
        },
        sistEndretAv: 'Redacted Redactesen',
        sistEndretDato: '2025-10-22T11:14:20.391Z',
    },
    {
        kode: 'DAGPENGEMOTTAKER_100',
        beskrivelse: '(Temp)Medlemmer med dagpenger under arbeidsløshet eller ventelønn m.m',
        vilkårshjemmel: {
            lovverk: 'Folketrygdloven',
            lovverksversjon: '2024-12-20',
            kapittel: '8',
            paragraf: '49',
            ledd: '3',
            setning: '1',
            bokstav: null,
        },
        sistEndretAv: 'Redacted Redactesen',
        sistEndretDato: '2025-10-22T11:14:20.391Z',
    },
]
