import { Testperson } from '@/mock-api/testpersoner/testpersoner'
import { søknadSchema } from '@/schemas/søknad'

const bosseGrunndata = {
    personId: 'bosse',
    personinfo: {
        fødselsnummer: '30816199456',
        aktørId: '3081619945600',
        navn: 'Bosse B Bunntrål',
        alder: 61,
    },
    soknader: [
        {
            id: '1b002e4f-1559-3415-a940-56eddf83e4d3',
            type: 'SELVSTENDIGE_OG_FRILANSERE',
            status: 'SENDT',
            fnr: '30816199456',
            sykmeldingId: '19f53de3-0259-44f4-a606-663162e4dae9',
            arbeidsgiver: null,
            arbeidssituasjon: 'FISKER',
            korrigerer: null,
            korrigertAv: null,
            soktUtenlandsopphold: false,
            arbeidsgiverForskutterer: null,
            fom: '2025-06-09',
            tom: '2025-06-15',
            dodsdato: null,
            startSyketilfelle: '2025-06-09',
            arbeidGjenopptatt: null,
            friskmeldt: null,
            sykmeldingSkrevet: '2025-06-09T02:00:00',
            opprettet: '2025-06-16T13:06:46.752112',
            opprinneligSendt: null,
            sendtNav: '2025-06-16T13:08:34.980122',
            sendtArbeidsgiver: null,
            egenmeldinger: null,
            fravarForSykmeldingen: [],
            papirsykmeldinger: [],
            fravar: [],
            andreInntektskilder: [{ type: 'FRILANSER_SELVSTENDIG', sykmeldt: false }],
            soknadsperioder: [
                {
                    fom: '2025-06-09',
                    tom: '2025-06-15',
                    sykmeldingsgrad: 100,
                    faktiskGrad: 11,
                    avtaltTimer: 37.5,
                    faktiskTimer: 4.0,
                    sykmeldingstype: 'AKTIVITET_IKKE_MULIG',
                    grad: 100,
                },
            ],
            sporsmal: [
                {
                    id: 'b3b9144d-3755-35d6-bb3b-14a1041c0555',
                    tag: 'ANSVARSERKLARING',
                    sporsmalstekst: 'Jeg bekrefter at jeg vil svare så riktig som jeg kan.',
                    undertekst: null,
                    min: null,
                    max: null,
                    svartype: 'CHECKBOX_PANEL',
                    kriterieForVisningAvUndersporsmal: null,
                    svar: [{ verdi: 'CHECKED' }],
                    undersporsmal: [],
                    metadata: null,
                },
                {
                    id: 'a328cad8-da2b-360b-add7-1292f96c1623',
                    tag: 'TILBAKE_I_ARBEID',
                    sporsmalstekst:
                        'Var du tilbake i fullt arbeid som selvstendig næringsdrivende før sykmeldingsperioden utløp 15. juni 2025?',
                    undertekst: null,
                    min: null,
                    max: null,
                    svartype: 'JA_NEI',
                    kriterieForVisningAvUndersporsmal: 'JA',
                    svar: [{ verdi: 'NEI' }],
                    undersporsmal: [
                        {
                            id: '46763d2a-3c8f-30b4-b669-3bd608bb89db',
                            tag: 'TILBAKE_NAR',
                            sporsmalstekst: 'Når begynte du å jobbe igjen?',
                            undertekst: null,
                            min: '2025-06-09',
                            max: '2025-06-15',
                            svartype: 'DATO',
                            kriterieForVisningAvUndersporsmal: null,
                            svar: [],
                            undersporsmal: [],
                            metadata: null,
                        },
                    ],
                    metadata: null,
                },
                {
                    id: '96d21235-814c-3da1-b12b-439f8af528d6',
                    tag: 'ARBEID_UNDERVEIS_100_PROSENT_0',
                    sporsmalstekst:
                        'I perioden 9. - 15. juni 2025 var du 100% sykmeldt som selvstendig næringsdrivende. Jobbet du noe i denne perioden?',
                    undertekst: null,
                    min: null,
                    max: null,
                    svartype: 'JA_NEI',
                    kriterieForVisningAvUndersporsmal: 'JA',
                    svar: [{ verdi: 'JA' }],
                    undersporsmal: [
                        {
                            id: '5cefd405-7016-316e-809d-7cf065fb5756',
                            tag: 'HVOR_MYE_HAR_DU_JOBBET_0',
                            sporsmalstekst: 'Oppgi arbeidsmengde i timer eller prosent:',
                            undertekst: null,
                            min: null,
                            max: null,
                            svartype: 'RADIO_GRUPPE_TIMER_PROSENT',
                            kriterieForVisningAvUndersporsmal: null,
                            svar: [],
                            undersporsmal: [
                                {
                                    id: '6775a14c-1254-33df-b8e9-f1853de7d541',
                                    tag: 'HVOR_MYE_PROSENT_0',
                                    sporsmalstekst: 'Prosent',
                                    undertekst: null,
                                    min: null,
                                    max: null,
                                    svartype: 'RADIO',
                                    kriterieForVisningAvUndersporsmal: 'CHECKED',
                                    svar: [],
                                    undersporsmal: [
                                        {
                                            id: '12129c3b-9f71-3793-9e6d-8a762bd54cef',
                                            tag: 'HVOR_MYE_PROSENT_VERDI_0',
                                            sporsmalstekst:
                                                'Oppgi hvor mange prosent av din normale arbeidstid du jobbet i perioden 9. - 15. juni 2025?',
                                            undertekst: 'Oppgi i prosent. Eksempel: 40',
                                            min: '1',
                                            max: '99',
                                            svartype: 'PROSENT',
                                            kriterieForVisningAvUndersporsmal: null,
                                            svar: [],
                                            undersporsmal: [],
                                            metadata: null,
                                        },
                                    ],
                                    metadata: null,
                                },
                                {
                                    id: '11ef6f99-8311-3ee2-9841-eae5a20ff8bc',
                                    tag: 'HVOR_MYE_TIMER_0',
                                    sporsmalstekst: 'Timer',
                                    undertekst: null,
                                    min: null,
                                    max: null,
                                    svartype: 'RADIO',
                                    kriterieForVisningAvUndersporsmal: 'CHECKED',
                                    svar: [{ verdi: 'CHECKED' }],
                                    undersporsmal: [
                                        {
                                            id: '7454e8b4-8875-3d6d-90ca-281808c9f0c4',
                                            tag: 'HVOR_MYE_TIMER_VERDI_0',
                                            sporsmalstekst:
                                                'Oppgi totalt antall timer du jobbet i perioden 9. - 15. juni 2025',
                                            undertekst: 'Eksempel: 8,5',
                                            min: '1',
                                            max: '150',
                                            svartype: 'TIMER',
                                            kriterieForVisningAvUndersporsmal: null,
                                            svar: [{ verdi: '4' }],
                                            undersporsmal: [],
                                            metadata: null,
                                        },
                                    ],
                                    metadata: null,
                                },
                            ],
                            metadata: null,
                        },
                        {
                            id: '9a44ae0d-7dad-3b34-b748-5d032a546c4a',
                            tag: 'JOBBER_DU_NORMAL_ARBEIDSUKE_0',
                            sporsmalstekst: 'Jobber du vanligvis 37,5 timer i uka?',
                            undertekst: null,
                            min: null,
                            max: null,
                            svartype: 'JA_NEI',
                            kriterieForVisningAvUndersporsmal: 'NEI',
                            svar: [{ verdi: 'JA' }],
                            undersporsmal: [
                                {
                                    id: 'b0cff6fa-a3e6-3918-82ac-8ad95660f546',
                                    tag: 'HVOR_MANGE_TIMER_PER_UKE_0',
                                    sporsmalstekst: 'Oppgi timer per uke',
                                    undertekst: 'Eksempel: 8,5',
                                    min: '1',
                                    max: '150',
                                    svartype: 'TIMER',
                                    kriterieForVisningAvUndersporsmal: null,
                                    svar: [],
                                    undersporsmal: [],
                                    metadata: null,
                                },
                            ],
                            metadata: null,
                        },
                    ],
                    metadata: null,
                },
                {
                    id: 'b0cceff1-eb5b-3f12-9032-e69edd2bbb50',
                    tag: 'ARBEID_UTENFOR_NORGE',
                    sporsmalstekst: 'Har du arbeidet i utlandet i løpet av de siste 12 månedene?',
                    undertekst: null,
                    min: null,
                    max: null,
                    svartype: 'JA_NEI',
                    kriterieForVisningAvUndersporsmal: null,
                    svar: [{ verdi: 'JA' }],
                    undersporsmal: [],
                    metadata: null,
                },
                {
                    id: '292a9342-944b-30a7-874f-a6e4390f34b6',
                    tag: 'ANDRE_INNTEKTSKILDER',
                    sporsmalstekst: 'Har du annen inntekt?',
                    undertekst: null,
                    min: null,
                    max: null,
                    svartype: 'JA_NEI',
                    kriterieForVisningAvUndersporsmal: 'JA',
                    svar: [{ verdi: 'JA' }],
                    undersporsmal: [
                        {
                            id: '48c713e2-b8cc-3b50-8683-5068794dd559',
                            tag: 'HVILKE_ANDRE_INNTEKTSKILDER',
                            sporsmalstekst: 'Hvilke inntektskilder har du?',
                            undertekst: null,
                            min: null,
                            max: null,
                            svartype: 'CHECKBOX_GRUPPE',
                            kriterieForVisningAvUndersporsmal: null,
                            svar: [],
                            undersporsmal: [
                                {
                                    id: '02a162c6-281a-3442-a86d-8db19112c948',
                                    tag: 'INNTEKTSKILDE_ARBEIDSFORHOLD',
                                    sporsmalstekst: 'arbeidsforhold',
                                    undertekst: null,
                                    min: null,
                                    max: null,
                                    svartype: 'CHECKBOX',
                                    kriterieForVisningAvUndersporsmal: 'CHECKED',
                                    svar: [],
                                    undersporsmal: [
                                        {
                                            id: '44964020-3ead-3a27-8adb-e7ce2be16f9a',
                                            tag: 'INNTEKTSKILDE_ARBEIDSFORHOLD_ER_DU_SYKMELDT',
                                            sporsmalstekst: 'Er du sykmeldt fra dette?',
                                            undertekst: null,
                                            min: null,
                                            max: null,
                                            svartype: 'JA_NEI',
                                            kriterieForVisningAvUndersporsmal: null,
                                            svar: [],
                                            undersporsmal: [],
                                            metadata: null,
                                        },
                                    ],
                                    metadata: null,
                                },
                                {
                                    id: '220c756f-8ebf-3add-ad69-f7f2116ce793',
                                    tag: 'INNTEKTSKILDE_JORDBRUKER',
                                    sporsmalstekst: 'jordbruk / fiske / reindrift',
                                    undertekst: null,
                                    min: null,
                                    max: null,
                                    svartype: 'CHECKBOX',
                                    kriterieForVisningAvUndersporsmal: 'CHECKED',
                                    svar: [],
                                    undersporsmal: [
                                        {
                                            id: 'b7ce3932-73e4-31c8-ba6f-ab6de91c2c59',
                                            tag: 'INNTEKTSKILDE_JORDBRUKER_ER_DU_SYKMELDT',
                                            sporsmalstekst: 'Er du sykmeldt fra dette?',
                                            undertekst: null,
                                            min: null,
                                            max: null,
                                            svartype: 'JA_NEI',
                                            kriterieForVisningAvUndersporsmal: null,
                                            svar: [],
                                            undersporsmal: [],
                                            metadata: null,
                                        },
                                    ],
                                    metadata: null,
                                },
                                {
                                    id: '8a661db7-f77c-3da3-9ae3-6f4a0a7dc53c',
                                    tag: 'INNTEKTSKILDE_FRILANSER_SELVSTENDIG',
                                    sporsmalstekst: 'frilanser',
                                    undertekst: null,
                                    min: null,
                                    max: null,
                                    svartype: 'CHECKBOX',
                                    kriterieForVisningAvUndersporsmal: 'CHECKED',
                                    svar: [{ verdi: 'CHECKED' }],
                                    undersporsmal: [
                                        {
                                            id: 'cb47acec-d78a-34be-93b9-cb70b2e50fdd',
                                            tag: 'INNTEKTSKILDE_FRILANSER_SELVSTENDIG_ER_DU_SYKMELDT',
                                            sporsmalstekst: 'Er du sykmeldt fra dette?',
                                            undertekst: null,
                                            min: null,
                                            max: null,
                                            svartype: 'JA_NEI',
                                            kriterieForVisningAvUndersporsmal: null,
                                            svar: [{ verdi: 'NEI' }],
                                            undersporsmal: [],
                                            metadata: null,
                                        },
                                    ],
                                    metadata: null,
                                },
                                {
                                    id: '4ee23d67-e1f8-3888-a687-1cbc97a7be07',
                                    tag: 'INNTEKTSKILDE_ANNET',
                                    sporsmalstekst: 'annet',
                                    undertekst: null,
                                    min: null,
                                    max: null,
                                    svartype: 'CHECKBOX',
                                    kriterieForVisningAvUndersporsmal: null,
                                    svar: [],
                                    undersporsmal: [],
                                    metadata: null,
                                },
                            ],
                            metadata: null,
                        },
                    ],
                    metadata: null,
                },
                {
                    id: 'ab4a71e6-d8e7-35fb-9e61-3e760d1ebd72',
                    tag: 'OPPHOLD_UTENFOR_EOS',
                    sporsmalstekst: 'Var du på reise utenfor EU/EØS mens du var sykmeldt 9. - 15. juni 2025?',
                    undertekst: null,
                    min: null,
                    max: null,
                    svartype: 'JA_NEI',
                    kriterieForVisningAvUndersporsmal: 'JA',
                    svar: [{ verdi: 'NEI' }],
                    undersporsmal: [
                        {
                            id: 'ea0902ef-451c-3661-92ab-cc294e61e6cf',
                            tag: 'OPPHOLD_UTENFOR_EOS_NAR',
                            sporsmalstekst: 'Når var du utenfor EU/EØS?',
                            undertekst: null,
                            min: '2025-06-09',
                            max: '2025-06-15',
                            svartype: 'PERIODER',
                            kriterieForVisningAvUndersporsmal: null,
                            svar: [],
                            undersporsmal: [],
                            metadata: null,
                        },
                    ],
                    metadata: null,
                },
                {
                    id: '6afab556-4bef-3365-833e-a64076f63ac7',
                    tag: 'INNTEKTSOPPLYSNINGER_VIRKSOMHETEN_AVVIKLET',
                    sporsmalstekst: 'Har du avviklet virksomheten din før du ble sykmeldt?',
                    undertekst: null,
                    min: null,
                    max: null,
                    svartype: 'RADIO_GRUPPE',
                    kriterieForVisningAvUndersporsmal: null,
                    svar: [],
                    undersporsmal: [
                        {
                            id: '4ed1cd4d-b1cc-3ff0-a510-1d183e3402b2',
                            tag: 'INNTEKTSOPPLYSNINGER_VIRKSOMHETEN_AVVIKLET_JA',
                            sporsmalstekst: 'Ja',
                            undertekst: null,
                            min: null,
                            max: null,
                            svartype: 'RADIO',
                            kriterieForVisningAvUndersporsmal: 'CHECKED',
                            svar: [],
                            undersporsmal: [
                                {
                                    id: '883f6e00-134b-3da3-b799-0a39994f8be0',
                                    tag: 'INNTEKTSOPPLYSNINGER_VIRKSOMHETEN_AVVIKLET_NAR',
                                    sporsmalstekst: 'Når ble virksomheten avviklet?',
                                    undertekst: null,
                                    min: null,
                                    max: '2025-06-08',
                                    svartype: 'DATO',
                                    kriterieForVisningAvUndersporsmal: null,
                                    svar: [],
                                    undersporsmal: [],
                                    metadata: null,
                                },
                            ],
                            metadata: null,
                        },
                        {
                            id: '1d921e83-6975-35a4-91c5-02b2699cddac',
                            tag: 'INNTEKTSOPPLYSNINGER_VIRKSOMHETEN_AVVIKLET_NEI',
                            sporsmalstekst: 'Nei',
                            undertekst: null,
                            min: null,
                            max: null,
                            svartype: 'RADIO',
                            kriterieForVisningAvUndersporsmal: 'CHECKED',
                            svar: [{ verdi: 'CHECKED' }],
                            undersporsmal: [
                                {
                                    id: 'a6efb1cc-2014-3443-8198-a19d2c19fbad',
                                    tag: 'INNTEKTSOPPLYSNINGER_NY_I_ARBEIDSLIVET',
                                    sporsmalstekst: 'Er du ny i arbeidslivet etter 1. januar 2020?',
                                    undertekst: null,
                                    min: null,
                                    max: null,
                                    svartype: 'RADIO_GRUPPE',
                                    kriterieForVisningAvUndersporsmal: null,
                                    svar: [],
                                    undersporsmal: [
                                        {
                                            id: 'c777171c-6af0-3074-becb-b31b13bc15e2',
                                            tag: 'INNTEKTSOPPLYSNINGER_NY_I_ARBEIDSLIVET_JA',
                                            sporsmalstekst: 'Ja',
                                            undertekst: null,
                                            min: null,
                                            max: null,
                                            svartype: 'RADIO',
                                            kriterieForVisningAvUndersporsmal: 'CHECKED',
                                            svar: [],
                                            undersporsmal: [
                                                {
                                                    id: '065ea1f6-f35c-37ab-9f1a-0346ce228b37',
                                                    tag: 'INNTEKTSOPPLYSNINGER_NY_I_ARBEIDSLIVET_DATO',
                                                    sporsmalstekst: 'Når begynte du i arbeidslivet?',
                                                    undertekst: null,
                                                    min: '2020-01-01',
                                                    max: '2025-06-08',
                                                    svartype: 'DATO',
                                                    kriterieForVisningAvUndersporsmal: null,
                                                    svar: [],
                                                    undersporsmal: [],
                                                    metadata: null,
                                                },
                                            ],
                                            metadata: null,
                                        },
                                        {
                                            id: 'bffa1d48-2493-3f47-a9d3-795c9a3aa03d',
                                            tag: 'INNTEKTSOPPLYSNINGER_NY_I_ARBEIDSLIVET_NEI',
                                            sporsmalstekst: 'Nei',
                                            undertekst: null,
                                            min: null,
                                            max: null,
                                            svartype: 'RADIO',
                                            kriterieForVisningAvUndersporsmal: 'CHECKED',
                                            svar: [{ verdi: 'CHECKED' }],
                                            undersporsmal: [
                                                {
                                                    id: 'd796a1a6-d74f-367f-844c-63124aecbb3c',
                                                    tag: 'INNTEKTSOPPLYSNINGER_VARIG_ENDRING',
                                                    sporsmalstekst:
                                                        'Har det skjedd en varig endring i arbeidssituasjonen eller virksomheten din i mellom 1. januar 2020 og frem tilsykmeldingstidspunktet?',
                                                    undertekst: null,
                                                    min: null,
                                                    max: null,
                                                    svartype: 'JA_NEI',
                                                    kriterieForVisningAvUndersporsmal: 'JA',
                                                    svar: [{ verdi: 'JA' }],
                                                    undersporsmal: [
                                                        {
                                                            id: '229feb32-7eeb-3a1a-b600-d24f2dd2288b',
                                                            tag: 'INNTEKTSOPPLYSNINGER_VARIG_ENDRING_BEGRUNNELSE',
                                                            sporsmalstekst:
                                                                'Hvilken endring har skjedd i din arbeidssituasjon eller virksomhet?',
                                                            undertekst: 'Du kan velge ett eller flere alternativer',
                                                            min: null,
                                                            max: null,
                                                            svartype: 'CHECKBOX_GRUPPE',
                                                            kriterieForVisningAvUndersporsmal: null,
                                                            svar: [],
                                                            undersporsmal: [
                                                                {
                                                                    id: '528f8512-1902-3fa6-902d-cea979e343ae',
                                                                    tag: 'INNTEKTSOPPLYSNINGER_VARIG_ENDRING_BEGRUNNELSE_OPPRETTELSE_NEDLEGGELSE',
                                                                    sporsmalstekst:
                                                                        'Opprettelse eller nedleggelse av næringsvirksomhet',
                                                                    undertekst: null,
                                                                    min: null,
                                                                    max: null,
                                                                    svartype: 'CHECKBOX',
                                                                    kriterieForVisningAvUndersporsmal: null,
                                                                    svar: [],
                                                                    undersporsmal: [],
                                                                    metadata: null,
                                                                },
                                                                {
                                                                    id: '83ca0a99-d8fb-3d77-8e93-9103bc0294da',
                                                                    tag: 'INNTEKTSOPPLYSNINGER_VARIG_ENDRING_BEGRUNNELSE_ENDRET_INNSATS',
                                                                    sporsmalstekst: 'Økt eller redusert innsats',
                                                                    undertekst: null,
                                                                    min: null,
                                                                    max: null,
                                                                    svartype: 'CHECKBOX',
                                                                    kriterieForVisningAvUndersporsmal: null,
                                                                    svar: [{ verdi: 'CHECKED' }],
                                                                    undersporsmal: [],
                                                                    metadata: null,
                                                                },
                                                                {
                                                                    id: '0c0648c3-d160-3232-8ab9-6dc58c1bb1b7',
                                                                    tag: 'INNTEKTSOPPLYSNINGER_VARIG_ENDRING_BEGRUNNELSE_OMLEGGING_AV_VIRKSOMHETEN',
                                                                    sporsmalstekst: 'Omlegging av virksomheten',
                                                                    undertekst: null,
                                                                    min: null,
                                                                    max: null,
                                                                    svartype: 'CHECKBOX',
                                                                    kriterieForVisningAvUndersporsmal: null,
                                                                    svar: [],
                                                                    undersporsmal: [],
                                                                    metadata: null,
                                                                },
                                                                {
                                                                    id: '4ce14147-7aff-35e5-ba05-ae1b6de9b4a1',
                                                                    tag: 'INNTEKTSOPPLYSNINGER_VARIG_ENDRING_BEGRUNNELSE_ENDRET_MARKEDSSITUASJON',
                                                                    sporsmalstekst: 'Endret markedssituasjon',
                                                                    undertekst: null,
                                                                    min: null,
                                                                    max: null,
                                                                    svartype: 'CHECKBOX',
                                                                    kriterieForVisningAvUndersporsmal: null,
                                                                    svar: [],
                                                                    undersporsmal: [],
                                                                    metadata: null,
                                                                },
                                                                {
                                                                    id: 'b3dccfb9-6b90-3827-aecb-3b0113331eff',
                                                                    tag: 'INNTEKTSOPPLYSNINGER_VARIG_ENDRING_BEGRUNNELSE_ANNET',
                                                                    sporsmalstekst: 'Annet',
                                                                    undertekst: null,
                                                                    min: null,
                                                                    max: null,
                                                                    svartype: 'CHECKBOX',
                                                                    kriterieForVisningAvUndersporsmal: null,
                                                                    svar: [],
                                                                    undersporsmal: [],
                                                                    metadata: null,
                                                                },
                                                            ],
                                                            metadata: null,
                                                        },
                                                        {
                                                            id: '5c603963-c5bf-3bb9-9bb4-f9f69f5c26f1',
                                                            tag: 'INNTEKTSOPPLYSNINGER_VARIG_ENDRING_25_PROSENT',
                                                            sporsmalstekst:
                                                                'Har du hatt mer enn 25 prosent endring i årsinntekten din som følge av den varige endringen?',
                                                            undertekst: null,
                                                            min: null,
                                                            max: null,
                                                            svartype: 'JA_NEI',
                                                            kriterieForVisningAvUndersporsmal: 'JA',
                                                            svar: [{ verdi: 'NEI' }],
                                                            undersporsmal: [
                                                                {
                                                                    id: '7890f353-532e-37f4-850c-96e9c0e7d09d',
                                                                    tag: 'INNTEKTSOPPLYSNINGER_VARIG_ENDRING_DATO',
                                                                    sporsmalstekst:
                                                                        'Når skjedde den siste varige endringen?',
                                                                    undertekst: null,
                                                                    min: '2020-01-01',
                                                                    max: '2025-06-09',
                                                                    svartype: 'DATO',
                                                                    kriterieForVisningAvUndersporsmal: null,
                                                                    svar: [],
                                                                    undersporsmal: [],
                                                                    metadata: null,
                                                                },
                                                            ],
                                                            metadata: null,
                                                        },
                                                    ],
                                                    metadata: null,
                                                },
                                            ],
                                            metadata: null,
                                        },
                                    ],
                                    metadata: null,
                                },
                            ],
                            metadata: null,
                        },
                    ],
                    metadata: null,
                },
                {
                    id: '386ffdc6-dacc-36f5-ba16-a98b6840c863',
                    tag: 'TIL_SLUTT',
                    sporsmalstekst: null,
                    undertekst: null,
                    min: null,
                    max: null,
                    svartype: 'OPPSUMMERING',
                    kriterieForVisningAvUndersporsmal: null,
                    svar: [{ verdi: 'true' }],
                    undersporsmal: [],
                    metadata: null,
                },
            ],
            avsendertype: 'BRUKER',
            ettersending: false,
            mottaker: null,
            egenmeldtSykmelding: false,
            yrkesskade: null,
            arbeidUtenforNorge: true,
            harRedusertVenteperiode: null,
            behandlingsdager: [],
            permitteringer: [],
            merknaderFraSykmelding: null,
            egenmeldingsdagerFraSykmelding: null,
            merknader: null,
            sendTilGosys: null,
            utenlandskSykmelding: false,
            medlemskapVurdering: null,
            forstegangssoknad: true,
            tidligereArbeidsgiverOrgnummer: null,
            fiskerBlad: 'B',
            inntektFraNyttArbeidsforhold: [],
            selvstendigNaringsdrivende: null,
            friskTilArbeidVedtakId: null,
            friskTilArbeidVedtakPeriode: null,
            fortsattArbeidssoker: null,
            inntektUnderveis: null,
            ignorerArbeidssokerregister: null,
        },
    ],
}

// Validate søknader with Zod schema
const validatedSoknader = bosseGrunndata.soknader.map((soknad) => søknadSchema.parse(soknad))

export const Bosse: Testperson = {
    ...bosseGrunndata,
    soknader: validatedSoknader,
    saksbehandlingsperioder: [],
    yrkesaktivitet: {},
    dagoversikt: {},
    dokumenter: {},
}
