import { Testperson } from '@/mock-api/testpersoner/testpersoner'

// Grunndata for Mattis
const mattisGrunndata = {
    personId: 'jf74h',
    personinfo: {
        fødselsnummer: '13065212348',
        aktørId: '1234567891011',
        navn: 'Mattis Matros',
        alder: 18,
    },
    soknader: [
        {
            id: 'ab0c5c03-0acf-3e42-a0cc-fa74281d5bba',
            type: 'SELVSTENDIGE_OG_FRILANSERE',
            status: 'SENDT',
            fnr: '22839399964',
            sykmeldingId: 'b8356ef5-7e88-4263-8fb6-0911dad44d0a',
            arbeidsgiver: null,
            arbeidssituasjon: 'FRILANSER',
            korrigerer: null,
            korrigertAv: null,
            soktUtenlandsopphold: false,
            arbeidsgiverForskutterer: null,
            fom: '2025-06-01',
            tom: '2025-06-24',
            dodsdato: null,
            startSyketilfelle: '2025-05-27',
            arbeidGjenopptatt: null,
            friskmeldt: null,
            sykmeldingSkrevet: '2025-06-18T02:00:00',
            opprettet: '2025-06-25T09:39:40.234825',
            opprinneligSendt: null,
            sendtNav: '2025-06-25T09:43:29.950974227',
            sendtArbeidsgiver: null,
            egenmeldinger: null,
            fravarForSykmeldingen: [],
            papirsykmeldinger: [],
            fravar: [],
            andreInntektskilder: [{ type: 'ARBEIDSFORHOLD', sykmeldt: true }],
            soknadsperioder: [
                {
                    fom: '2025-06-01',
                    tom: '2025-06-24',
                    sykmeldingsgrad: 100,
                    faktiskGrad: 7,
                    avtaltTimer: 4.0,
                    faktiskTimer: 1.0,
                    sykmeldingstype: 'AKTIVITET_IKKE_MULIG',
                    grad: 100,
                },
            ],
            sporsmal: [
                {
                    id: '2306df0f-2e0f-3439-8fbd-11a7828f13fd',
                    tag: 'ANSVARSERKLARING',
                    sporsmalstekst: 'Jeg bekrefter at jeg vil svare så riktig som jeg kan.',
                    undertekst: null,
                    min: null,
                    max: null,
                    svartype: 'CHECKBOX_PANEL',
                    kriterieForVisningAvUndersporsmal: null,
                    svar: [{ verdi: 'CHECKED' }],
                    undersporsmal: [],
                    metadata: null,
                },
                {
                    id: '6fd6570e-a779-3333-89ef-44d567d5dc5d',
                    tag: 'TILBAKE_I_ARBEID',
                    sporsmalstekst:
                        'Var du tilbake i fullt arbeid som frilanser før sykmeldingsperioden utløp 24. juni 2025?',
                    undertekst: null,
                    min: null,
                    max: null,
                    svartype: 'JA_NEI',
                    kriterieForVisningAvUndersporsmal: 'JA',
                    svar: [{ verdi: 'NEI' }],
                    undersporsmal: [
                        {
                            id: '6a348d55-7b71-3f77-bbdd-6185e97e8109',
                            tag: 'TILBAKE_NAR',
                            sporsmalstekst: 'Når begynte du å jobbe igjen?',
                            undertekst: null,
                            min: '2025-06-01',
                            max: '2025-06-24',
                            svartype: 'DATO',
                            kriterieForVisningAvUndersporsmal: null,
                            svar: [],
                            undersporsmal: [],
                            metadata: null,
                        },
                    ],
                    metadata: null,
                },
                {
                    id: '61f0b9d1-e61d-3980-8c74-3c4e3e0aa5c0',
                    tag: 'ARBEID_UNDERVEIS_100_PROSENT_0',
                    sporsmalstekst:
                        'I perioden 1. - 24. juni 2025 var du 100% sykmeldt som frilanser. Jobbet du noe i denne perioden?',
                    undertekst: null,
                    min: null,
                    max: null,
                    svartype: 'JA_NEI',
                    kriterieForVisningAvUndersporsmal: 'JA',
                    svar: [{ verdi: 'JA' }],
                    undersporsmal: [
                        {
                            id: '6f539fe8-e2b6-3248-acbd-246a0ce6f3a9',
                            tag: 'HVOR_MYE_HAR_DU_JOBBET_0',
                            sporsmalstekst: 'Oppgi arbeidsmengde i timer eller prosent:',
                            undertekst: null,
                            min: null,
                            max: null,
                            svartype: 'RADIO_GRUPPE_TIMER_PROSENT',
                            kriterieForVisningAvUndersporsmal: null,
                            svar: [],
                            undersporsmal: [
                                {
                                    id: '09fdb095-32fe-3aee-9647-08fa83d6d53e',
                                    tag: 'HVOR_MYE_PROSENT_0',
                                    sporsmalstekst: 'Prosent',
                                    undertekst: null,
                                    min: null,
                                    max: null,
                                    svartype: 'RADIO',
                                    kriterieForVisningAvUndersporsmal: 'CHECKED',
                                    svar: [],
                                    undersporsmal: [
                                        {
                                            id: 'c523ad25-5f4f-3510-94e3-8cdd9cd27561',
                                            tag: 'HVOR_MYE_PROSENT_VERDI_0',
                                            sporsmalstekst:
                                                'Oppgi hvor mange prosent av din normale arbeidstid du jobbet i perioden 1. - 24. juni 2025?',
                                            undertekst: 'Oppgi i prosent. Eksempel: 40',
                                            min: '1',
                                            max: '99',
                                            svartype: 'PROSENT',
                                            kriterieForVisningAvUndersporsmal: null,
                                            svar: [],
                                            undersporsmal: [],
                                            metadata: null,
                                        },
                                    ],
                                    metadata: null,
                                },
                                {
                                    id: '96e037de-bb48-3cf0-96ba-a4e71df9269b',
                                    tag: 'HVOR_MYE_TIMER_0',
                                    sporsmalstekst: 'Timer',
                                    undertekst: null,
                                    min: null,
                                    max: null,
                                    svartype: 'RADIO',
                                    kriterieForVisningAvUndersporsmal: 'CHECKED',
                                    svar: [{ verdi: 'CHECKED' }],
                                    undersporsmal: [
                                        {
                                            id: 'aa9f510e-1454-33b4-9fac-d4e84e3aa9fe',
                                            tag: 'HVOR_MYE_TIMER_VERDI_0',
                                            sporsmalstekst:
                                                'Oppgi totalt antall timer du jobbet i perioden 1. - 24. juni 2025',
                                            undertekst: 'Eksempel: 8,5',
                                            min: '1',
                                            max: '514',
                                            svartype: 'TIMER',
                                            kriterieForVisningAvUndersporsmal: null,
                                            svar: [{ verdi: '1' }],
                                            undersporsmal: [],
                                            metadata: null,
                                        },
                                    ],
                                    metadata: null,
                                },
                            ],
                            metadata: null,
                        },
                        {
                            id: '5dff6227-e0dd-3bcf-8228-d2d31c7b67a8',
                            tag: 'JOBBER_DU_NORMAL_ARBEIDSUKE_0',
                            sporsmalstekst: 'Jobber du vanligvis 37,5 timer i uka?',
                            undertekst: null,
                            min: null,
                            max: null,
                            svartype: 'JA_NEI',
                            kriterieForVisningAvUndersporsmal: 'NEI',
                            svar: [{ verdi: 'NEI' }],
                            undersporsmal: [
                                {
                                    id: '64173fca-448d-3575-9023-8794e8b5b28b',
                                    tag: 'HVOR_MANGE_TIMER_PER_UKE_0',
                                    sporsmalstekst: 'Oppgi timer per uke',
                                    undertekst: 'Eksempel: 8,5',
                                    min: '1',
                                    max: '150',
                                    svartype: 'TIMER',
                                    kriterieForVisningAvUndersporsmal: null,
                                    svar: [{ verdi: '4' }],
                                    undersporsmal: [],
                                    metadata: null,
                                },
                            ],
                            metadata: null,
                        },
                    ],
                    metadata: null,
                },
                {
                    id: 'c82c7756-cfa4-3987-9883-30957931e804',
                    tag: 'ARBEID_UTENFOR_NORGE',
                    sporsmalstekst: 'Har du arbeidet i utlandet i løpet av de siste 12 månedene?',
                    undertekst: null,
                    min: null,
                    max: null,
                    svartype: 'JA_NEI',
                    kriterieForVisningAvUndersporsmal: null,
                    svar: [{ verdi: 'NEI' }],
                    undersporsmal: [],
                    metadata: null,
                },
                {
                    id: 'c2bd0790-61c6-32ad-8a3a-e7903af796ea',
                    tag: 'ANDRE_INNTEKTSKILDER',
                    sporsmalstekst: 'Har du annen inntekt? Du trenger ikke oppgi penger fra NAV.',
                    undertekst: null,
                    min: null,
                    max: null,
                    svartype: 'JA_NEI',
                    kriterieForVisningAvUndersporsmal: 'JA',
                    svar: [{ verdi: 'JA' }],
                    undersporsmal: [
                        {
                            id: '9fe5421f-7a23-3535-85f8-7c6ed766a68e',
                            tag: 'HVILKE_ANDRE_INNTEKTSKILDER',
                            sporsmalstekst: 'Hvilke inntektskilder har du?',
                            undertekst: null,
                            min: null,
                            max: null,
                            svartype: 'CHECKBOX_GRUPPE',
                            kriterieForVisningAvUndersporsmal: null,
                            svar: [],
                            undersporsmal: [
                                {
                                    id: 'c8e4f93b-4656-38d5-bc16-c68ebc8ba4c0',
                                    tag: 'INNTEKTSKILDE_ARBEIDSFORHOLD',
                                    sporsmalstekst: 'arbeidsforhold',
                                    undertekst: null,
                                    min: null,
                                    max: null,
                                    svartype: 'CHECKBOX',
                                    kriterieForVisningAvUndersporsmal: 'CHECKED',
                                    svar: [{ verdi: 'CHECKED' }],
                                    undersporsmal: [
                                        {
                                            id: '27102c90-7b36-3454-ac4b-6d7e6e3b95b7',
                                            tag: 'INNTEKTSKILDE_ARBEIDSFORHOLD_ER_DU_SYKMELDT',
                                            sporsmalstekst: 'Er du sykmeldt fra dette?',
                                            undertekst: null,
                                            min: null,
                                            max: null,
                                            svartype: 'JA_NEI',
                                            kriterieForVisningAvUndersporsmal: null,
                                            svar: [{ verdi: 'JA' }],
                                            undersporsmal: [],
                                            metadata: null,
                                        },
                                    ],
                                    metadata: null,
                                },
                                {
                                    id: 'cc1cd990-30c7-3b16-b653-75f14efda83d',
                                    tag: 'INNTEKTSKILDE_JORDBRUKER',
                                    sporsmalstekst: 'jordbruk / fiske / reindrift',
                                    undertekst: null,
                                    min: null,
                                    max: null,
                                    svartype: 'CHECKBOX',
                                    kriterieForVisningAvUndersporsmal: 'CHECKED',
                                    svar: [],
                                    undersporsmal: [
                                        {
                                            id: '036ddd49-99c6-3468-a450-7d8b9b1c7f8b',
                                            tag: 'INNTEKTSKILDE_JORDBRUKER_ER_DU_SYKMELDT',
                                            sporsmalstekst: 'Er du sykmeldt fra dette?',
                                            undertekst: null,
                                            min: null,
                                            max: null,
                                            svartype: 'JA_NEI',
                                            kriterieForVisningAvUndersporsmal: null,
                                            svar: [],
                                            undersporsmal: [],
                                            metadata: null,
                                        },
                                    ],
                                    metadata: null,
                                },
                                {
                                    id: '326ff6b5-44c1-3c73-88ce-f2f851e433e8',
                                    tag: 'INNTEKTSKILDE_FRILANSER_SELVSTENDIG',
                                    sporsmalstekst: 'selvstendig næringsdrivende',
                                    undertekst: null,
                                    min: null,
                                    max: null,
                                    svartype: 'CHECKBOX',
                                    kriterieForVisningAvUndersporsmal: 'CHECKED',
                                    svar: [],
                                    undersporsmal: [
                                        {
                                            id: '8c903a18-9327-309c-9078-14c3d0133f76',
                                            tag: 'INNTEKTSKILDE_FRILANSER_SELVSTENDIG_ER_DU_SYKMELDT',
                                            sporsmalstekst: 'Er du sykmeldt fra dette?',
                                            undertekst: null,
                                            min: null,
                                            max: null,
                                            svartype: 'JA_NEI',
                                            kriterieForVisningAvUndersporsmal: null,
                                            svar: [],
                                            undersporsmal: [],
                                            metadata: null,
                                        },
                                    ],
                                    metadata: null,
                                },
                                {
                                    id: 'eb35b45c-ef76-3272-8459-5a91009d50ad',
                                    tag: 'INNTEKTSKILDE_ANNET',
                                    sporsmalstekst: 'annet',
                                    undertekst: null,
                                    min: null,
                                    max: null,
                                    svartype: 'CHECKBOX',
                                    kriterieForVisningAvUndersporsmal: null,
                                    svar: [],
                                    undersporsmal: [],
                                    metadata: null,
                                },
                            ],
                            metadata: null,
                        },
                    ],
                    metadata: null,
                },
                {
                    id: '9fc5ec1c-da47-364d-91da-bb58c9351117',
                    tag: 'OPPHOLD_UTENFOR_EOS',
                    sporsmalstekst: 'Var du på reise utenfor EU/EØS mens du var sykmeldt 1. - 24. juni 2025?',
                    undertekst: null,
                    min: null,
                    max: null,
                    svartype: 'JA_NEI',
                    kriterieForVisningAvUndersporsmal: 'JA',
                    svar: [{ verdi: 'NEI' }],
                    undersporsmal: [
                        {
                            id: '58330260-d1d4-32bc-afad-9ab180d44906',
                            tag: 'OPPHOLD_UTENFOR_EOS_NAR',
                            sporsmalstekst: 'Når var du utenfor EU/EØS?',
                            undertekst: null,
                            min: '2025-06-01',
                            max: '2025-06-24',
                            svartype: 'PERIODER',
                            kriterieForVisningAvUndersporsmal: null,
                            svar: [],
                            undersporsmal: [],
                            metadata: null,
                        },
                    ],
                    metadata: null,
                },
                {
                    id: 'd6799908-2582-31d0-922e-0f426a09d49e',
                    tag: 'TIL_SLUTT',
                    sporsmalstekst: null,
                    undertekst: null,
                    min: null,
                    max: null,
                    svartype: 'OPPSUMMERING',
                    kriterieForVisningAvUndersporsmal: null,
                    svar: [{ verdi: 'true' }],
                    undersporsmal: [],
                    metadata: null,
                },
            ],
            avsendertype: 'BRUKER',
            ettersending: false,
            mottaker: 'NAV',
            egenmeldtSykmelding: false,
            yrkesskade: null,
            arbeidUtenforNorge: false,
            harRedusertVenteperiode: false,
            behandlingsdager: [],
            permitteringer: [],
            merknaderFraSykmelding: null,
            egenmeldingsdagerFraSykmelding: null,
            merknader: null,
            sendTilGosys: null,
            utenlandskSykmelding: false,
            medlemskapVurdering: null,
            forstegangssoknad: true,
            tidligereArbeidsgiverOrgnummer: null,
            fiskerBlad: null,
            inntektFraNyttArbeidsforhold: [],
            selvstendigNaringsdrivende: null,
            friskTilArbeidVedtakId: null,
            friskTilArbeidVedtakPeriode: null,
            fortsattArbeidssoker: null,
            inntektUnderveis: null,
            ignorerArbeidssokerregister: null,
        },
        {
            id: '41141069-932a-3c3d-b44d-d9c976011131',
            type: 'ARBEIDSTAKERE',
            status: 'SENDT',
            fnr: '22839399964',
            sykmeldingId: 'ce9771ac-5b35-45c0-96a3-fcda62619fce',
            arbeidsgiver: { navn: 'Danskebåten', orgnummer: '889955555' },
            arbeidssituasjon: 'ARBEIDSTAKER',
            korrigerer: null,
            korrigertAv: null,
            soktUtenlandsopphold: false,
            arbeidsgiverForskutterer: null,
            fom: '2025-05-27',
            tom: '2025-06-24',
            dodsdato: null,
            startSyketilfelle: '2025-05-27',
            arbeidGjenopptatt: '2025-06-22',
            friskmeldt: null,
            sykmeldingSkrevet: '2025-06-18T02:00:00',
            opprettet: '2025-06-25T09:39:26.243663',
            opprinneligSendt: null,
            sendtNav: '2025-06-25T09:42:25.770395757',
            sendtArbeidsgiver: '2025-06-25T09:42:25.770395757',
            egenmeldinger: null,
            fravarForSykmeldingen: [],
            papirsykmeldinger: [],
            fravar: [{ fom: '2025-06-17', tom: '2025-06-17', type: 'FERIE' }],
            andreInntektskilder: [{ type: 'FRILANSER', sykmeldt: null }],
            soknadsperioder: [
                {
                    fom: '2025-05-27',
                    tom: '2025-06-24',
                    sykmeldingsgrad: 100,
                    faktiskGrad: 4,
                    avtaltTimer: 37.5,
                    faktiskTimer: 5.0,
                    sykmeldingstype: 'AKTIVITET_IKKE_MULIG',
                    grad: 100,
                },
            ],
            sporsmal: [
                {
                    id: '4a3d2b59-9996-3650-a21d-2d8187fe608d',
                    tag: 'ANSVARSERKLARING',
                    sporsmalstekst: 'Jeg bekrefter at jeg vil svare så riktig som jeg kan.',
                    undertekst: null,
                    min: null,
                    max: null,
                    svartype: 'CHECKBOX_PANEL',
                    kriterieForVisningAvUndersporsmal: null,
                    svar: [{ verdi: 'CHECKED' }],
                    undersporsmal: [],
                    metadata: null,
                },
                {
                    id: '36799973-9afa-3897-a277-08725cfa489c',
                    tag: 'TILBAKE_I_ARBEID',
                    sporsmalstekst:
                        'Var du tilbake i fullt arbeid hos Danskebåten i løpet av perioden 27. mai - 24. juni 2025?',
                    undertekst: null,
                    min: null,
                    max: null,
                    svartype: 'JA_NEI',
                    kriterieForVisningAvUndersporsmal: 'JA',
                    svar: [{ verdi: 'JA' }],
                    undersporsmal: [
                        {
                            id: '01a02747-f697-3bb1-a163-451ece2aa8a0',
                            tag: 'TILBAKE_NAR',
                            sporsmalstekst: 'Når begynte du å jobbe igjen?',
                            undertekst: null,
                            min: '2025-05-27',
                            max: '2025-06-24',
                            svartype: 'DATO',
                            kriterieForVisningAvUndersporsmal: null,
                            svar: [{ verdi: '2025-06-22' }],
                            undersporsmal: [],
                            metadata: null,
                        },
                    ],
                    metadata: null,
                },
                {
                    id: 'b7f3b76b-a4a3-3b16-b550-a44eef3251c5',
                    tag: 'FERIE_V2',
                    sporsmalstekst: 'Tok du ut feriedager i tidsrommet 27. mai - 21. juni 2025?',
                    undertekst: null,
                    min: null,
                    max: null,
                    svartype: 'JA_NEI',
                    kriterieForVisningAvUndersporsmal: 'JA',
                    svar: [{ verdi: 'JA' }],
                    undersporsmal: [
                        {
                            id: '1317d8af-4c1c-31de-9694-f5628d80151c',
                            tag: 'FERIE_NAR_V2',
                            sporsmalstekst: 'Når tok du ut feriedager?',
                            undertekst: null,
                            min: '2025-05-27',
                            max: '2025-06-21',
                            svartype: 'PERIODER',
                            kriterieForVisningAvUndersporsmal: null,
                            svar: [{ verdi: '{"fom":"2025-06-17","tom":"2025-06-17"}' }],
                            undersporsmal: [],
                            metadata: null,
                        },
                    ],
                    metadata: null,
                },
                {
                    id: 'a5d18e74-6ee8-3e8a-9e0b-ed9462b108b1',
                    tag: 'PERMISJON_V2',
                    sporsmalstekst: 'Tok du permisjon mens du var sykmeldt 27. mai - 21. juni 2025?',
                    undertekst: null,
                    min: null,
                    max: null,
                    svartype: 'JA_NEI',
                    kriterieForVisningAvUndersporsmal: 'JA',
                    svar: [{ verdi: 'NEI' }],
                    undersporsmal: [
                        {
                            id: 'c9201eb3-a29f-301f-9163-6c7b53aab4fc',
                            tag: 'PERMISJON_NAR_V2',
                            sporsmalstekst: 'Når tok du permisjon?',
                            undertekst: null,
                            min: '2025-05-27',
                            max: '2025-06-21',
                            svartype: 'PERIODER',
                            kriterieForVisningAvUndersporsmal: null,
                            svar: [],
                            undersporsmal: [],
                            metadata: null,
                        },
                    ],
                    metadata: null,
                },
                {
                    id: 'acf96815-6db4-34f1-9478-81e4f8c07703',
                    tag: 'ARBEID_UNDERVEIS_100_PROSENT_0',
                    sporsmalstekst:
                        'I perioden 27. mai - 21. juni 2025 var du 100 % sykmeldt fra Danskebåten. Jobbet du noe hos Danskebåten i denne perioden?',
                    undertekst: null,
                    min: null,
                    max: null,
                    svartype: 'JA_NEI',
                    kriterieForVisningAvUndersporsmal: 'JA',
                    svar: [{ verdi: 'JA' }],
                    undersporsmal: [
                        {
                            id: 'ab4e3b11-00d5-349d-aa8a-816765de62cb',
                            tag: 'HVOR_MYE_HAR_DU_JOBBET_0',
                            sporsmalstekst: 'Oppgi arbeidsmengde i timer eller prosent:',
                            undertekst: null,
                            min: null,
                            max: null,
                            svartype: 'RADIO_GRUPPE_TIMER_PROSENT',
                            kriterieForVisningAvUndersporsmal: null,
                            svar: [],
                            undersporsmal: [
                                {
                                    id: '12888978-d2f0-3ddd-b7b6-d52e5238a02e',
                                    tag: 'HVOR_MYE_PROSENT_0',
                                    sporsmalstekst: 'Prosent',
                                    undertekst: null,
                                    min: null,
                                    max: null,
                                    svartype: 'RADIO',
                                    kriterieForVisningAvUndersporsmal: 'CHECKED',
                                    svar: [],
                                    undersporsmal: [
                                        {
                                            id: '22c6b296-e1a5-3292-822f-d87dc7671ead',
                                            tag: 'HVOR_MYE_PROSENT_VERDI_0',
                                            sporsmalstekst:
                                                'Oppgi hvor mange prosent av din normale arbeidstid du jobbet hos Danskebåten i perioden 27. mai - 21. juni 2025?',
                                            undertekst: 'Oppgi i prosent. Eksempel: 40',
                                            min: '1',
                                            max: '99',
                                            svartype: 'PROSENT',
                                            kriterieForVisningAvUndersporsmal: null,
                                            svar: [],
                                            undersporsmal: [],
                                            metadata: null,
                                        },
                                    ],
                                    metadata: null,
                                },
                                {
                                    id: '4aa68f62-7c14-3de9-983a-f4f01e3024b6',
                                    tag: 'HVOR_MYE_TIMER_0',
                                    sporsmalstekst: 'Timer',
                                    undertekst: null,
                                    min: null,
                                    max: null,
                                    svartype: 'RADIO',
                                    kriterieForVisningAvUndersporsmal: 'CHECKED',
                                    svar: [{ verdi: 'CHECKED' }],
                                    undersporsmal: [
                                        {
                                            id: '514bd008-15d7-3e0b-98b4-43318ce8177f',
                                            tag: 'HVOR_MYE_TIMER_VERDI_0',
                                            sporsmalstekst:
                                                'Oppgi totalt antall timer du jobbet i perioden 27. mai - 21. juni 2025 hos Danskebåten',
                                            undertekst: 'Eksempel: 8,5',
                                            min: '1',
                                            max: '557',
                                            svartype: 'TIMER',
                                            kriterieForVisningAvUndersporsmal: null,
                                            svar: [{ verdi: '5' }],
                                            undersporsmal: [],
                                            metadata: null,
                                        },
                                    ],
                                    metadata: null,
                                },
                            ],
                            metadata: null,
                        },
                        {
                            id: '2d8a008c-792a-356f-abf5-a1c910d05ea0',
                            tag: 'JOBBER_DU_NORMAL_ARBEIDSUKE_0',
                            sporsmalstekst: 'Jobber du vanligvis 37,5 timer i uka hos Danskebåten?',
                            undertekst: null,
                            min: null,
                            max: null,
                            svartype: 'JA_NEI',
                            kriterieForVisningAvUndersporsmal: 'NEI',
                            svar: [{ verdi: 'JA' }],
                            undersporsmal: [
                                {
                                    id: '0aa038d8-593e-3e95-b8ba-bfb24ba44482',
                                    tag: 'HVOR_MANGE_TIMER_PER_UKE_0',
                                    sporsmalstekst: 'Oppgi timer per uke',
                                    undertekst: 'Eksempel: 8,5',
                                    min: '1',
                                    max: '150',
                                    svartype: 'TIMER',
                                    kriterieForVisningAvUndersporsmal: null,
                                    svar: [],
                                    undersporsmal: [],
                                    metadata: null,
                                },
                            ],
                            metadata: null,
                        },
                    ],
                    metadata: null,
                },
                {
                    id: '3993af4b-9f14-3881-9034-185a9b660344',
                    tag: 'ARBEID_UTENFOR_NORGE',
                    sporsmalstekst: 'Har du arbeidet i utlandet i løpet av de siste 12 månedene?',
                    undertekst: null,
                    min: null,
                    max: null,
                    svartype: 'JA_NEI',
                    kriterieForVisningAvUndersporsmal: null,
                    svar: [{ verdi: 'NEI' }],
                    undersporsmal: [],
                    metadata: null,
                },
                {
                    id: 'b0f3f2f4-00bd-384b-9661-9016ec6c1911',
                    tag: 'ANDRE_INNTEKTSKILDER_V2',
                    sporsmalstekst: 'Har du andre inntektskilder enn Danskebåten?',
                    undertekst: null,
                    min: null,
                    max: null,
                    svartype: 'JA_NEI',
                    kriterieForVisningAvUndersporsmal: 'JA',
                    svar: [{ verdi: 'JA' }],
                    undersporsmal: [
                        {
                            id: 'f8ce871b-bc9a-36a2-9f5a-19f6fba9b37d',
                            tag: 'HVILKE_ANDRE_INNTEKTSKILDER',
                            sporsmalstekst: 'Velg inntektskildene som passer for deg:',
                            undertekst: 'Finner du ikke noe som passer for deg, svarer du nei på spørsmålet over',
                            min: null,
                            max: null,
                            svartype: 'CHECKBOX_GRUPPE',
                            kriterieForVisningAvUndersporsmal: null,
                            svar: [],
                            undersporsmal: [
                                {
                                    id: '0982c86f-3f3a-3df4-b964-7722169d9a8f',
                                    tag: 'INNTEKTSKILDE_ANDRE_ARBEIDSFORHOLD',
                                    sporsmalstekst: 'Ansatt andre steder enn nevnt over',
                                    undertekst: null,
                                    min: null,
                                    max: null,
                                    svartype: 'CHECKBOX',
                                    kriterieForVisningAvUndersporsmal: 'CHECKED',
                                    svar: [],
                                    undersporsmal: [
                                        {
                                            id: 'f4a476f4-0d45-3c0d-b104-f28f3963d661',
                                            tag: 'INNTEKTSKILDE_ANDRE_ARBEIDSFORHOLD_JOBBET_I_DET_SISTE',
                                            sporsmalstekst:
                                                'Har du jobbet for eller mottatt inntekt fra én eller flere av disse arbeidsgiverne de siste 14 dagene før du ble sykmeldt?',
                                            undertekst: null,
                                            min: null,
                                            max: null,
                                            svartype: 'JA_NEI',
                                            kriterieForVisningAvUndersporsmal: null,
                                            svar: [],
                                            undersporsmal: [],
                                            metadata: null,
                                        },
                                    ],
                                    metadata: null,
                                },
                                {
                                    id: '95b871d1-8019-3b1d-a295-b2222280d4f4',
                                    tag: 'INNTEKTSKILDE_SELVSTENDIG',
                                    sporsmalstekst: 'Selvstendig næringsdrivende',
                                    undertekst: null,
                                    min: null,
                                    max: null,
                                    svartype: 'CHECKBOX',
                                    kriterieForVisningAvUndersporsmal: null,
                                    svar: [],
                                    undersporsmal: [],
                                    metadata: null,
                                },
                                {
                                    id: '12011ccf-ca6e-3210-831a-fba77f6cf940',
                                    tag: 'INNTEKTSKILDE_SELVSTENDIG_DAGMAMMA',
                                    sporsmalstekst: 'Dagmamma',
                                    undertekst: null,
                                    min: null,
                                    max: null,
                                    svartype: 'CHECKBOX',
                                    kriterieForVisningAvUndersporsmal: null,
                                    svar: [],
                                    undersporsmal: [],
                                    metadata: null,
                                },
                                {
                                    id: 'e8811d01-11fc-3063-8f06-be609d98d586',
                                    tag: 'INNTEKTSKILDE_JORDBRUKER',
                                    sporsmalstekst: 'Jordbruk / Fiske / Reindrift',
                                    undertekst: null,
                                    min: null,
                                    max: null,
                                    svartype: 'CHECKBOX',
                                    kriterieForVisningAvUndersporsmal: null,
                                    svar: [],
                                    undersporsmal: [],
                                    metadata: null,
                                },
                                {
                                    id: 'f2bf8ca2-c4c6-3b7d-9911-4ed395efa26a',
                                    tag: 'INNTEKTSKILDE_FRILANSER',
                                    sporsmalstekst: 'Frilanser',
                                    undertekst: null,
                                    min: null,
                                    max: null,
                                    svartype: 'CHECKBOX',
                                    kriterieForVisningAvUndersporsmal: null,
                                    svar: [{ verdi: 'CHECKED' }],
                                    undersporsmal: [],
                                    metadata: null,
                                },
                                {
                                    id: '399def56-dd8f-3533-8d79-4e8cb8ced02a',
                                    tag: 'INNTEKTSKILDE_OMSORGSLONN',
                                    sporsmalstekst: 'Kommunal omsorgstønad',
                                    undertekst: null,
                                    min: null,
                                    max: null,
                                    svartype: 'CHECKBOX',
                                    kriterieForVisningAvUndersporsmal: null,
                                    svar: [],
                                    undersporsmal: [],
                                    metadata: null,
                                },
                                {
                                    id: '15b875e0-8458-3131-9ceb-d2c13a674c77',
                                    tag: 'INNTEKTSKILDE_FOSTERHJEM',
                                    sporsmalstekst: 'Fosterhjemsgodtgjørelse',
                                    undertekst: null,
                                    min: null,
                                    max: null,
                                    svartype: 'CHECKBOX',
                                    kriterieForVisningAvUndersporsmal: null,
                                    svar: [],
                                    undersporsmal: [],
                                    metadata: null,
                                },
                                {
                                    id: '9ba3cb4e-864e-39f3-a3d7-a0f08c77a51d',
                                    tag: 'INNTEKTSKILDE_STYREVERV',
                                    sporsmalstekst: 'Styreverv',
                                    undertekst: null,
                                    min: null,
                                    max: null,
                                    svartype: 'CHECKBOX',
                                    kriterieForVisningAvUndersporsmal: null,
                                    svar: [],
                                    undersporsmal: [],
                                    metadata: null,
                                },
                            ],
                            metadata: null,
                        },
                    ],
                    metadata: {
                        kjenteInntektskilder: [
                            {
                                navn: 'Danskebåten',
                                kilde: 'SYKMELDING',
                                orgnummer: '889955555',
                            },
                        ],
                    },
                },
                {
                    id: 'a5e093d2-0284-3719-bbef-aa843abc4cc7',
                    tag: 'OPPHOLD_UTENFOR_EOS',
                    sporsmalstekst: 'Var du på reise utenfor EU/EØS mens du var sykmeldt 27. mai - 21. juni 2025?',
                    undertekst: null,
                    min: null,
                    max: null,
                    svartype: 'JA_NEI',
                    kriterieForVisningAvUndersporsmal: 'JA',
                    svar: [{ verdi: 'NEI' }],
                    undersporsmal: [
                        {
                            id: '72630bb5-9728-3f3d-acba-3ea81315c6c7',
                            tag: 'OPPHOLD_UTENFOR_EOS_NAR',
                            sporsmalstekst: 'Når var du utenfor EU/EØS?',
                            undertekst: null,
                            min: '2025-05-27',
                            max: '2025-06-21',
                            svartype: 'PERIODER',
                            kriterieForVisningAvUndersporsmal: null,
                            svar: [],
                            undersporsmal: [],
                            metadata: null,
                        },
                    ],
                    metadata: null,
                },
                {
                    id: '54210974-95fc-3bbd-9fbe-71f6d8a41bcd',
                    tag: 'TIL_SLUTT',
                    sporsmalstekst: null,
                    undertekst: null,
                    min: null,
                    max: null,
                    svartype: 'OPPSUMMERING',
                    kriterieForVisningAvUndersporsmal: null,
                    svar: [{ verdi: 'true' }],
                    undersporsmal: [],
                    metadata: null,
                },
            ],
            avsendertype: 'BRUKER',
            ettersending: false,
            mottaker: 'ARBEIDSGIVER_OG_NAV',
            egenmeldtSykmelding: false,
            yrkesskade: null,
            arbeidUtenforNorge: false,
            harRedusertVenteperiode: null,
            behandlingsdager: [],
            permitteringer: [],
            merknaderFraSykmelding: null,
            egenmeldingsdagerFraSykmelding: null,
            merknader: null,
            sendTilGosys: null,
            utenlandskSykmelding: false,
            medlemskapVurdering: null,
            forstegangssoknad: true,
            tidligereArbeidsgiverOrgnummer: null,
            fiskerBlad: null,
            inntektFraNyttArbeidsforhold: [],
            selvstendigNaringsdrivende: null,
            friskTilArbeidVedtakId: null,
            friskTilArbeidVedtakPeriode: null,
            fortsattArbeidssoker: null,
            inntektUnderveis: null,
            ignorerArbeidssokerregister: null,
        },
    ],
}

export const Mattis: Testperson = {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    ...(mattisGrunndata as any),
    saksbehandlingsperioder: [],
    yrkesaktivitet: {},
    dagoversikt: {},
    dokumenter: {},
}
