name: "Installs node, installs pnpm dependencies with cache"
description: "Builds a Next.JS App, creates a docker image and uploads it to GAR"

inputs:
  app:
    required: true
    description: "Name of the application"
  env:
    required: true
    description: "Deployment environment (dev, demo, prod)"
  identity_provider:
    required: true
    description: "Workload identity provider for GAR access"
  project_id:
    required: true
    description: "GCP project ID for GAR"
  team:
    required: true
    default: "speilvendt"
    description: "Team speilvendt"
  NPM_AUTH_TOKEN:
    required: true
    description: "NPM authentication token"
outputs:
  image:
    description: "Docker image in GAR"
    value: ${{ steps.docker-build-push.outputs.image }}

runs:
  using: "composite"
  steps:
    - uses: navikt/helse-spillerom/actions/pnpm-cached@main
      with:
        NPM_AUTH_TOKEN: ${{ inputs.NPM_AUTH_TOKEN }}
    - name: Copy appropriate env file to root
      shell: bash
      env:
        DEPLOY_ENV: ${{ inputs.env }}
      run: |
        echo "Copying .nais/envs/.env.${DEPLOY_ENV}..."
        cp ".nais/envs/.env.${DEPLOY_ENV}" .env.production
    - id: pnpm-run-build
      shell: bash
      env:
        NEXT_PUBLIC_VERSION: ${{ github.sha }}
      run: pnpm run build
    - name: Upload static files to NAV CDN
      uses: nais/deploy/actions/cdn-upload/v2@master
      with:
        team: ${{ inputs.team }}
        source: ./.next/static
        destination: /${{ inputs.app }}/_next
        identity_provider: ${{ inputs.identity_provider }}
        project_id: ${{ inputs.project_id }}
    - name: Push docker image to GAR
      uses: nais/docker-build-push@v0
      id: docker-build-push
      env:
        ACTIONS_RUNTIME_TOKEN: ${{ inputs.NPM_AUTH_TOKEN }}
      with:
        team: ${{ inputs.team }}
        identity_provider: ${{ inputs.identity_provider }}
        project_id: ${{ inputs.project_id }}
        image_suffix: ${{ inputs.env }}
